### ISSUE TITLE
Command-line arguments for hoptimator-operator

### ISSUE THREAD

**Issue by ryannedolan** [linkedin/Hoptimator#17]
Currently `hoptimator-operator` accepts one argument, the path to a Calcite "model file". Remaining properties are hard-coded, including the K8s namespace ("default"). We need a way to provide a few additional command-line arguments, e.g. `--namespace my-namespace`, along with sensible defaults.

Additionally, individual controllers/reconcilers may need to be configured with their own properties. Controllers are pluggable, so we need a way to pass arbitrary key-value properties via command-line arguments, e.g. `--property key=value`. Controllers should be able to see these properties via the Operator object, e.g. `Operator.properties().get("key")`.

**Comment by stevenewald** [comment]
Would you mind giving an example of how to test this?

**Comment by ryannedolan** [comment]
Hmm, this turns out to be difficult to test, cuz operator properties really shouldn't be observable from the SQL layer. For example, say we want the kafka topic controller to have a configurable partition count or retention period for new topics. Those are specific to Kafka, and have no bearing on the results you'd see from a query. So we could pass those properties on the command line to the operator, and the kafka controller could change its behavior accordingly, but you wouldn't be able to test that from the SQL CLI.

Or e.g. if you change the k8s namespace used by the operator,  or the service account used by the operator, that sort of thing should be invisible to the SQL layer. That's by design!

So I don't think we can test this within SQL, unless we do something artificial. I'd rather we write a unit test (if there is anything unit-testable) or just test it manually. I'd probably add a log line to the operator that spits out all the properties, and then just look for my properties to show up. For a manual test, you can modify `hoptimator-operator-deployment.yaml` to include additional command-line arguments.

One thing that's worth manually testing is the k8s namespace. It's not uncommon to run an operator in one namespace but have it control resources in another namespace. The dev environment uses the "default" namespace, but it should be possible to modify `hoptimator-operator-deployment.yaml` to pass `--namespace foo` to the operator. That would enable you to create KafkaTopics, Subscriptions, etc in the foo namespace, e.g. `kubectl apply -n foo -f deploy/samples`, and the operator should see them. If we can document that this works in the PR, we don't need to bother automating a test for it.
