### ISSUE TITLE
Support multiple planner output dialects

### ISSUE THREAD

**Issue by ryannedolan** [linkedin/Hoptimator#24]
The planner is currently hard-coded to output MySQL dialect, which Flink natively understands. In order to target additional runtimes, we need a way to generate SQL in other dialects. N.B. the planner is largely dialect-agnostic already, until you ask for the plan as a String.

**Comment by HoganEdwardChu** [comment]
Hi, I didn't mean to disturb you, I was watching with interest. The line that you mean is here? https://github.com/linkedin/Hoptimator/blob/f748776207ad49858b2cb0628966995fdf337a03/hoptimator-planner/src/main/java/com/linkedin/hoptimator/planner/PipelineRel.java#L39

**Comment by ryannedolan** [comment]
> The line that you mean is here?

Yep. It looks like the hard-coded dialect is only used in a couple methods that return SQL strings. It might make sense to change those to return the underlying ScriptImplementer, which is dialect agnostic. Then callers could do `rel.query(...).sql(dialect)` and get whatever dialect they want.

**Comment by HoganEdwardChu** [comment]
Oh... you mean https://github.com/HoganEdwardChu/Hoptimator/pull/1/files this way? But than i think we have to get input dialect

**Comment by HoganEdwardChu** [comment]
Thanks for the detailed and contextual explanation. I'll think about what you said too. (if there's a good direction, I'll try it and share it again too!) Implmenting alternative runtimes Spark SQL instead of Flink SQL would be awesome.

**Comment by ryannedolan** [comment]
I haven't given much thought to how we'd support multiple runtimes in the operator. There is a flink adapter, which is really the only place in the control plane that we assume the SQL will run on flink: https://github.com/linkedin/Hoptimator/blob/main/hoptimator-flink-adapter/src/main/java/com/linkedin/hoptimator/operator/flink/FlinkSqlJobReconciler.java#L57

As you can see, the flink adapter just passes the SQL from `SqlJob` to a `FlinkDeployment` (which is handled by the external flink-kubernetes-operator). Theoretically, we could do something similar for Spark or any other SQL runtime. I'm not sure how valuable that would be, but it seems possible.

**Comment by HoganEdwardChu** [comment]
I guess I'll have to think about it a bit. If you have any good opinions on whether it is better to put a dialect in the pipeline, please proceed. I will continue to try. I think making another adapter should be postponed to a later date. I think the most important thing is to handle the flink job well.

**Comment by HoganEdwardChu** [comment]
I think adding sqlDialect to pipeline is best at this point 
https://github.com/HoganEdwardChu/Hoptimator/blob/90f4c459e1bb71f79c2625f19d79753eb0fbfbd5/hoptimator-planner/src/main/java/com/linkedin/hoptimator/planner/PipelineRel.java#L95

**Comment by ryannedolan** [comment]
> adding sqlDialect to pipeline

Makes sense to me!

**Comment by ryannedolan** [comment]
Thanks @HoganEdwardChu  for #31

**Comment by HoganEdwardChu** [comment]
Thanks!!!!!

I am trying to add another sql time like spark. If there is any valuable progress I will pr!  @ryannedolan
