### ISSUE TITLE
CLI logs are too verbose

### ISSUE THREAD

**Issue by ryannedolan** [linkedin/Hoptimator#36]
The CLI and operator currently use `slf4j-simple` with default configuration. This is too verbose for the CLI, as Flink generates a ton of logs.

**Comment by HoganEdwardChu** [comment]
Hi, I didn't mean to disturb you, I was watching with interest. You mean like this https://github.com/HoganEdwardChu/Hoptimator/pull/2

**Comment by HoganEdwardChu** [comment]
I agree with you! I think using system property with sl4j-simple that way is much more explicit than custom log4j configuration
